version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.10.0
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
      # - ./assets/img:/srv/jekyll/assets
    command: jekyll serve --host 0.0.0.0 --port 8080 --watch 

